version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_URI=mongodb://db:27017/shopping-cart
    depends_on:
      - db

  db:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
